export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const START_DATE_CHANGE='START_DATE_CHANGE';
export const END_DATE_CHANGE='END_DATE_CHANGE';
export const ENABLE_CHANGE='ENABLE_CHANGE';