export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const DATE_CHANGE='DATE_CHANGE';
export const ENABLE_CHANGE='ENABLE_CHANGE';